-- MySQL Script generated by MySQL Workbench
-- jue 13 feb 2020 11:57:37 EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`def_unidad_negocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`def_unidad_negocio` (
  `iddef_unidad_negocio` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL DEFAULT ' ',
  `estado` TINYINT(4) NOT NULL DEFAULT 1 COMMENT '0 => inactivo\n1 => Activo\n2 => cancelado\n',
  `fecha_creacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de Creación',
  `usuario_creacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `usuario_ultima_modificacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `fecha_ultima_modificacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de la ultima modificación',
  PRIMARY KEY (`iddef_unidad_negocio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`def_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`def_categoria` (
  `iddef_categoria` INT NOT NULL AUTO_INCREMENT,
  `iddef_unidad_negocio` INT NOT NULL DEFAULT 0,
  `iddef_categoria_padre` INT NOT NULL DEFAULT 0,
  `descripcion` VARCHAR(45) NOT NULL DEFAULT ' ',
  `estado` TINYINT(4) NOT NULL DEFAULT 1 COMMENT '0 => inactivo\n1 => Activo\n2 => cancelado\n',
  `fecha_creacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de Creación',
  `usuario_creacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `usuario_ultima_modificacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `fecha_ultima_modificacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de la ultima modificación',
  PRIMARY KEY (`iddef_categoria`),
  INDEX `fk_def_categoria_1_idx` (`iddef_unidad_negocio` ASC),
  CONSTRAINT `fk_def_categoria_1`
    FOREIGN KEY (`iddef_unidad_negocio`)
    REFERENCES `mydb`.`def_unidad_negocio` (`iddef_unidad_negocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`def_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`def_actividad` (
  `iddef_actividad` INT NOT NULL AUTO_INCREMENT,
  `iddef_categoria` INT NOT NULL DEFAULT 0,
  `descripcion` VARCHAR(45) NOT NULL DEFAULT ' ',
  `estado` TINYINT(4) NOT NULL DEFAULT 1 COMMENT '0 => inactivo\n1 => Activo\n2 => cancelado\n',
  `fecha_creacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de Creación',
  `usuario_creacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `usuario_ultima_modificacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `fecha_ultima_modificacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de la ultima modificación',
  PRIMARY KEY (`iddef_actividad`),
  INDEX `fk_def_actividad_1_idx` (`iddef_categoria` ASC),
  CONSTRAINT `fk_def_actividad_1`
    FOREIGN KEY (`iddef_categoria`)
    REFERENCES `mydb`.`def_categoria` (`iddef_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`def_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`def_horario` (
  `iddef_horario` INT NOT NULL AUTO_INCREMENT,
  `iddef_actividad` INT NOT NULL DEFAULT 0,
  `descripcion` VARCHAR(45) NOT NULL DEFAULT ' ',
  `estado` TINYINT(4) NOT NULL DEFAULT 1 COMMENT '0 => inactivo\n1 => Activo\n2 => cancelado\n',
  `fecha_creacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de Creación',
  `usuario_creacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `usuario_ultima_modificacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `fecha_ultima_modificacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de la ultima modificación',
  PRIMARY KEY (`iddef_horario`),
  INDEX `fk_def_horario_1_idx` (`iddef_actividad` ASC),
  CONSTRAINT `fk_def_horario_1`
    FOREIGN KEY (`iddef_actividad`)
    REFERENCES `mydb`.`def_actividad` (`iddef_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`def_restriccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`def_restriccion` (
  `iddef_restriccion` INT NOT NULL AUTO_INCREMENT,
  `iddef_actividad` INT NOT NULL DEFAULT 0,
  `descripcion` VARCHAR(45) NOT NULL DEFAULT ' ',
  `estado` TINYINT(4) NOT NULL DEFAULT 1 COMMENT '0 => inactivo\n1 => Activo\n2 => cancelado\n',
  `fecha_creacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de Creación',
  `usuario_creacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `usuario_ultima_modificacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `fecha_ultima_modificacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de la ultima modificación',
  PRIMARY KEY (`iddef_restriccion`),
  INDEX `fk_def_restriccion_1_idx` (`iddef_actividad` ASC),
  CONSTRAINT `fk_def_restriccion_1`
    FOREIGN KEY (`iddef_actividad`)
    REFERENCES `mydb`.`def_actividad` (`iddef_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`def_paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`def_paquete` (
  `iddef_paquete` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL DEFAULT ' ',
  `estado` TINYINT(4) NOT NULL DEFAULT 1 COMMENT '0 => inactivo\n1 => Activo\n2 => cancelado\n',
  `fecha_creacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de Creación',
  `usuario_creacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `usuario_ultima_modificacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `fecha_ultima_modificacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de la ultima modificación',
  PRIMARY KEY (`iddef_paquete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`def_paquete_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`def_paquete_categoria` (
  `iddef_paquete_categoria` INT NOT NULL AUTO_INCREMENT,
  `iddef_paquete` INT NOT NULL DEFAULT 0,
  `iddef_categoria` INT NOT NULL DEFAULT 0,
  `descripcion` VARCHAR(45) NOT NULL DEFAULT ' ',
  `estado` TINYINT(4) NOT NULL DEFAULT 1 COMMENT '0 => inactivo\n1 => Activo\n2 => cancelado\n',
  `fecha_creacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de Creación',
  `usuario_creacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `usuario_ultima_modificacion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT ' ',
  `fecha_ultima_modificacion` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'Fecha de la ultima modificación',
  PRIMARY KEY (`iddef_paquete_categoria`),
  INDEX `fk_def_paquete_categoria_1_idx` (`iddef_paquete` ASC),
  INDEX `fk_def_paquete_categoria_2_idx` (`iddef_categoria` ASC),
  CONSTRAINT `fk_def_paquete_categoria_1`
    FOREIGN KEY (`iddef_paquete`)
    REFERENCES `mydb`.`def_paquete` (`iddef_paquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_def_paquete_categoria_2`
    FOREIGN KEY (`iddef_categoria`)
    REFERENCES `mydb`.`def_categoria` (`iddef_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
